# Generated by Django 2.2.24 on 2021-08-12 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('typeCloth', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cloth', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='SizeGuide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurements', models.ManyToManyField(to='recommendSize.Measurement')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('inventory', models.ManyToManyField(to='recommendSize.ClothingItem')),
                ('sizeguide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendSize.SizeGuide')),
            ],
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='sizeguide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendSize.SizeGuide'),
        ),
    ]
